### ISSUE TITLE
Sprite1 Direction 

### ISSUE THREAD

**Issue by athens77** [Gallo-ICS2O1a/repel-assignment-maria-sofia-stella-athena#2]
Sprite1 only repels in certain directions (for example, only moves diagonally forward and backward and not any other directions when the player ellipse gets close)

**Comment by MrGallo** [comment]
Code:

```python
    direction = hypotenuse.heading()  
```
Plug that into `PVector.fromAngle()` to create a new `PVector` pointing in the appropriate direction.
Then, `.add()` that new `PVector` to the sprite's speed, or use it to modify the sprite's location.

```python
    playerangle = player.heading()
    sprite1angle = sprite1.heading()
```
This info is irrelevant. All you need is the `distance` measurement for the if-statement.
